---
env:
  global:
    - TF_VERSION="0.12.4"
    - DEP_VERSION="v0.5.4"

branches:
  only:
    - master
    - terraform011

sudo: required

language: go

before_install:
  - wget https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip -O /tmp/terraform.zip && sudo unzip -d /usr/local/bin/ /tmp/terraform.zip
  - wget https://github.com/golang/dep/releases/download/${DEP_VERSION}/dep-linux-amd64 -O /tmp/dep && sudo chmod +x /tmp/dep && sudo mv /tmp/dep /usr/local/bin/dep
  - touch Makefile

script:
  - terraform init
  - terraform fmt -check=true
  - dep ensure -vendor-only
  - echo 'package main' > main.go
  - go test -v -timeout=30m ./...

notifications:
  email:
    recipients:
      - yrochnyak@gmail.com
    on_success: change
    on_failure: change
