---
defaults: &defaults
  docker:
    - image: circleci/golang:1.12

  environment:
    DEP_VERSION: "v0.5.4"
    TF_VERSION: "0.11.14"

install_test_deps: &install_test_deps
  name: install test dependencies
  command: |
    curl -L -s https://github.com/golang/dep/releases/download/${DEP_VERSION}/dep-linux-amd64 -o /go/bin/dep && chmod +x /go/bin/dep
    curl -L -s https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip -o /go/bin/terraform.zip && unzip /go/bin/terraform.zip -d /go/bin && chmod +x /go/bin/terraform

filters: &filters
  branches:
    only:
      - master
      - terraform011

version: 2
jobs:
  lint:
    <<: *defaults
    working_directory: /go/src/github.com/grem11n/terraform-aws-vpc-peering
    steps:
      - checkout
      - run:
          <<: *install_test_deps
      - run: terraform init
      - run: terraform fmt -check=true
      - run: terraform validate -check-variables=false

  test:
    <<: *defaults
    working_directory: /go/src/github.com/grem11n/terraform-aws-vpc-peering
    steps:
      - checkout
      - run:
          <<: *install_test_deps
      - run: dep ensure -vendor-only
      - run: echo 'package main' > main.go
      - run: go test -v -timeout=30m ./...

workflows:
  version: 2
  lint-and-test:
    jobs:
      - lint:
          filters:
            <<: *filters
      - test:
          filters:
            <<: *filters
          requires:
            - lint
