# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    branches:
      only:
        - master
        - terraform011
        - tests011
    docker:
      # specify the version
      - image: circleci/golang:1.12

    environment:
      DEP_VERSION: "v0.5.4"
      TF_VERSION: "0.11.14"

    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - checkout
      - run: curl -L -s https://github.com/golang/dep/releases/download/${DEP_VERSION}/dep-linux-amd64 -o /go/bin/dep && chmod +x /go/bin/dep
      - run: curl -L -s https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip -o /go/bin/terraform.zip && unzip /go/bin/terraform.zip -d /go/bin && chmod +x /go/bin/terraform
      - run: terraform init
      - run: terraform fmt -check=true
      - run: terraform validate -check-variables=false
      - run: dep ensure -vendor-only
      - run: go test -v -timeout=30m test/.
