---
name: terraform-aws-vpc-peering
on:
  push:
    branches:
      - master
      - terraform011
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  build:
    name: terraform-fmt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Install Build Dependencies
        env:
          TF_VERSION: "0.12.10"
        run: >
          wget https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip -O /tmp/terraform.zip &&
          sudo unzip -d /tmp/ /tmp/terraform.zip &&
          sudo mv /tmp/terraform /usr/local/bin/

      - name: Check Format
        run: >
          terraform init &&
          terraform fmt -check=true
